In [3]:
import pandas as pd

air_data = pd.read_csv('Project1_Data/AirQuality_Daily_StudentVersion(in).csv')
air_data = pd.DataFrame(air_data)

In [3]:
def assign_temperature(temperature):
    if temperature < 32:
        return 'Below freezing'
    elif 32 <= temperature < 50:
        return 'Cool'
    elif 50 <= temperature < 70:
        return 'Warm'
    else:
        return 'Hot'

air_data['temperature_level'] = air_data['temperature'].apply(assign_temperature)

In [4]:
def assign_altitude(altitude):
    if altitude < 2000:
        return 'Low'
    elif 2000 <= altitude <= 3000:
        return 'Medium'
    else:
        return 'High'

air_data['altitude_level'] = air_data['sensor.altitude'].apply(assign_altitude)

In [17]:
def assign_humidity(humidity):
    if humidity < 50:
        return 'Low'
    elif 50 <= humidity < 80:
        return 'High'
    else:
        return 'Very high'

air_data['humidity_level'] = air_data['humidity'].apply(assign_humidity)

In [5]:
air_data_grouped = air_data.groupby(['sensor.name'])


air_data_aggregated_pm2_5 = air_data_grouped.agg(median_pm2_5 = ('pm2.5_atm', 'median'),
                                                  mean_pm2_5 = ('pm2.5_atm', 'mean'))
top_5_pm2_5 = air_data_aggregated_pm2_5.sort_values(by='mean_pm2_5', ascending=False).head(5)


air_data_aggregated_pm10_0 = air_data_grouped.agg(median_pm10_0 = ('pm10.0_atm', 'median'),
                                                  mean_pm10_0 = ('pm10.0_atm', 'mean'))
top_5_pm10_0 = air_data_aggregated_pm10_0.sort_values(by='mean_pm10_0', ascending=False).head(5)


air_data_aggregated_voc = air_data_grouped.agg(median_voc = ('voc', 'median'),
                                                mean_voc = ('voc', 'mean'))
top_5_voc = air_data_aggregated_voc.sort_values(by='mean_voc', ascending=False).head(5)


print(top_5_pm2_5)
print(top_5_pm10_0)
print(top_5_voc)

                                                    median_pm2_5  mean_pm2_5
sensor.name
Broken Bow                                             36.050240  928.710593
#16 - Richardson County Courthouse                     11.977344  700.127342
#18 - Southeast District Health Department- Tec...     10.322875  613.175352
NCDHD O'Neill #11                                       7.251208  164.495078
Swnphd-mccook                                           4.582281  123.011622
                                                    median_pm10_0  mean_pm10_0
sensor.name
Broken Bow                                              43.179094   929.678512
#16 - Richardson County Courthouse                      13.305615   701.632446
#18 - Southeast District Health Department- Tec...      11.433729   614.227248
NCDHD O'Neill #11                                        8.427437   166.132578
Swnphd-mccook                                            5.372073   124.227336
                                       median_voc    mean_voc
sensor.name
Swnphd-ogallala                        423.082292  399.434240
FCHD-YPS                               375.383500  372.462720
Three Rivers Public Health Department  376.810167  370.216208
ELVPHD Norfolk HD 4                    368.580500  360.833744
Swnphd-mccook                          381.468479  353.941581

In [19]:
max_pm2_5 = air_data.loc[air_data['pm2.5_atm'].idxmax()]

max_pm2_5

date                                          2/18/2025
monitor_index                                    195317
humidity                                            NaN
pressure                                            NaN
temperature                                         NaN
voc                                                 NaN
analog_input                                       0.07
pm2.5_alt                                        1.7125
pm1.0_atm                                   3781.691896
pm2.5_atm                                   3782.823313
pm10.0_atm                                  3784.682542
sensor.latitude                                 40.0622
sensor.longitude                               -95.6024
sensor.altitude                                    1023
sensor.name          #16 - Richardson County Courthouse
temperature_level                                   Hot
altitude_level                                      Low
humidity_level                                Very high
Name: 7561, dtype: object

In [18]:
max_pm10_0 = air_data.loc[air_data['pm10.0_atm'].idxmax()]

max_pm10_0

date                                          2/18/2025
monitor_index                                    195317
humidity                                            NaN
pressure                                            NaN
temperature                                         NaN
voc                                                 NaN
analog_input                                       0.07
pm2.5_alt                                        1.7125
pm1.0_atm                                   3781.691896
pm2.5_atm                                   3782.823313
pm10.0_atm                                  3784.682542
sensor.latitude                                 40.0622
sensor.longitude                               -95.6024
sensor.altitude                                    1023
sensor.name          #16 - Richardson County Courthouse
temperature_level                                   Hot
altitude_level                                      Low
humidity_level                                Very high
Name: 7561, dtype: object

In [20]:
max_voc = air_data.loc[air_data['voc'].idxmax()]

max_voc

date                       6/24/2024
monitor_index                 195541
humidity                    9.883429
pressure                  897.678857
temperature               116.455286
voc                      1209.931571
analog_input                0.010429
pm2.5_alt                   1.642857
pm1.0_atm                   1.066643
pm2.5_atm                   1.408286
pm10.0_atm                  1.799071
sensor.latitude            41.128284
sensor.longitude          -101.72022
sensor.altitude                 3220
sensor.name          Swnphd-ogallala
temperature_level                Hot
altitude_level                  High
humidity_level                   Low
Name: 2391, dtype: object

In [23]:
humidity_level_avg_pm2_5 = air_data.groupby('humidity_level')['pm2.5_atm'].mean()
humidity_level_avg_pm10_0 = air_data.groupby('humidity_level')['pm10.0_atm'].mean()
humidity_level_avg_voc = air_data.groupby('humidity_level')['voc'].mean()

print(humidity_level_avg_pm2_5,
    humidity_level_avg_pm10_0,
    humidity_level_avg_voc)

humidity_level
High          80.874444
Low           76.513935
Very high    533.786399
Name: pm2.5_atm, dtype: float64 humidity_level
High          82.561133
Low           77.880520
Very high    536.520850
Name: pm10.0_atm, dtype: float64 humidity_level
High         252.664069
Low          279.329347
Very high     19.395555
Name: voc, dtype: float64

In [24]:
temperature_level_avg_pm2_5 = air_data.groupby('temperature_level')['pm2.5_atm'].mean()
temperature_level_avg_pm10_0 = air_data.groupby('temperature_level')['pm10.0_atm'].mean()
temperature_level_avg_voc = air_data.groupby('temperature_level')['voc'].mean()

print(temperature_level_avg_pm2_5,
    temperature_level_avg_pm10_0,
    temperature_level_avg_voc)

temperature_level
Below freezing    273.698560
Cool              143.167452
Hot                70.145543
Warm               85.914999
Name: pm2.5_atm, dtype: float64 temperature_level
Below freezing    276.080794
Cool              144.593363
Hot                71.821037
Warm               86.834046
Name: pm10.0_atm, dtype: float64 temperature_level
Below freezing    257.628626
Cool              288.558923
Hot               282.145818
Warm              255.179179
Name: voc, dtype: float64

In [25]:
altitude_level_avg_pm2_5 = air_data.groupby('altitude_level')['pm2.5_atm'].mean()
altitude_level_avg_pm10_0 = air_data.groupby('altitude_level')['pm10.0_atm'].mean()
altitude_level_avg_voc = air_data.groupby('altitude_level')['voc'].mean()

print(altitude_level_avg_pm2_5,
    altitude_level_avg_pm10_0,
    altitude_level_avg_voc)

altitude_level
High        7.856594
Low        91.964518
Medium    162.633015
Name: pm2.5_atm, dtype: float64 altitude_level
High        8.999231
Low        93.593349
Medium    164.001230
Name: pm10.0_atm, dtype: float64 altitude_level
High      324.971952
Low       252.218398
Medium    282.205860
Name: voc, dtype: float64

In [28]:
unhealthy_pm2_5 = air_data[air_data['pm2.5_atm'] > 35.5]

pm2_5_unhealthy = unhealthy_pm2_5[['date', 'sensor.name', 'pm2.5_atm']]
pm2_5_unhealthy

,date,sensor.name,pm2.5_atm
370,3/29/2024,ELVPHD Wisner HD 5,39.761896
377,3/29/2024,ELVPHD Norfolk HD 4,38.425396
529,4/6/2024,TRPHD Harlan Co. Courthouse 24,37.819938
544,4/6/2024,Swnphd-ogallala,39.169042
1341,5/14/2024,ELVPHD Wisner HD 5,48.140771
...,...,...,...
8274,3/23/2025,Swnphd-mccook,981.919875
8291,3/24/2025,#18 - Southeast District Health Department- Te...,1692.498333
8293,3/24/2025,NCDHD O'Neill #11,1714.236813
8294,3/24/2025,Broken Bow,1713.840375
8295,3/24/2025,Swnphd-mccook,563.337313

In [29]:
unhealthy_pm10_0 = air_data[air_data['pm10.0_atm'] > 155]

pm10_0_unhealthy = unhealthy_pm2_5[['date', 'sensor.name', 'pm10.0_atm']]
pm10_0_unhealthy

,date,sensor.name,pm10.0_atm
370,3/29/2024,ELVPHD Wisner HD 5,50.163333
377,3/29/2024,ELVPHD Norfolk HD 4,43.370375
529,4/6/2024,TRPHD Harlan Co. Courthouse 24,43.793979
544,4/6/2024,Swnphd-ogallala,46.152625
1341,5/14/2024,ELVPHD Wisner HD 5,60.299813
...,...,...,...
8274,3/23/2025,Swnphd-mccook,982.185500
8291,3/24/2025,#18 - Southeast District Health Department- Te...,1692.793896
8293,3/24/2025,NCDHD O'Neill #11,1714.360500
8294,3/24/2025,Broken Bow,1713.964083
8295,3/24/2025,Swnphd-mccook,564.363833